### PR TITLE
UI: Prevent terminal scroll on progress bar update (#94)

### LINKED ISSUE #94: Scrolling up while running backdoor is impossible
[kotenok2000]

When i run backdoor on n00dles and scroll up terminal resets down when progress bar moves.

- [ ] Save file
- [ ] Minimal scripts to reproduce the issue
- [x] Steps to reproduce
- [x] Version of the game:1.7.0

### PR DESCRIPTION
**Pull request by bezrodnov**
UI: Prevent terminal scroll on progress bar update

closes #94 

Tested locally in the browser after starting server via `npm run start:dev`

### CODE REVIEW

File: src/Terminal/ui/TerminalActionTimer.tsx [hunk 1]
```diff
@@ -0,0 +1,26 @@
...
+export function TerminalActionTimer(): React.ReactElement {
+  const rerender = useRerender();
+
+  useEffect(() => {
+    const debounced = _.debounce(rerender, 25, { maxWait: 50 });
+    const unsubscribe = TerminalProcessEvents.subscribe(debounced);
+    return () => {
+      debounced.cancel();
+      unsubscribe();
+    };
```
Comment (Snarling) [inline src/Terminal/ui/TerminalActionTimer.tsx:18]:
```suggestion
import Typography from "@mui/material/Typography";

import { useRerender } from "../../ui/React/hooks";
import { Terminal } from "../../Terminal";
import { TerminalProcessEvents } from "../TerminalEvents";

export function TerminalActionTimer(): React.ReactElement {
  const rerender = useRerender();

  useEffect(() => {
    const unsubscribe = TerminalProcessEvents.subscribe(rerender);
    return unsubscribe;
```

Comment (Snarling) [inline src/Terminal/ui/TerminalActionTimer.tsx]:
```suggestion
import Typography from "@mui/material/Typography";

import { useRerender } from "../../ui/React/hooks";
import { Terminal } from "../../Terminal";
import { TerminalProcessEvents } from "../TerminalEvents";

export function TerminalActionTimer(): React.ReactElement {
  const rerender = useRerender();

  useEffect(() => {
    const unsubscribe = TerminalProcessEvents.subscribe(rerender);
    return unsubscribe;
```
Debounce is not needed here, it's needed for other terminal stuff because they could happen at arbitrarily fast rates (because the trigger is controlled by the player), but here we're only rerendering every time the terminal process function is ran, which should be a fixed time of approximately once every 200ms.

File: src/Terminal/Terminal.ts [hunk 2]
```diff
@@ -102,7 +102,7 @@ export class Terminal {
     if (this.action === null) return;
     this.action.timeLeft -= (CONSTANTS.MilliPerCycle * cycles) / 1000;
     if (this.action.timeLeft < 0.01) this.finishAction(false);
-    TerminalEvents.emit();
+    TerminalProcessEvents.emit();
```
Comment (Snarling) [inline src/Terminal/Terminal.ts]:
```suggestion
    else TerminalProcessEvents.emit();
```
Only need to send a process event if there is still an action underway. Without the debounce (see other suggestion), sending the event anyway leads to the action timer trying to rerender when there's no action.

**Review by Snarling — CHANGES_REQUESTED** [review]
See suggested changes for removing the debounce from the timer. Another option would be to just remove the TerminalProcessEvents emitter entirely, and just do a useRerender(200) to handle rerendering the action bar. With that the action bar would need to check if the action was null and return `<></>` if so, since the rerender might hit during a time window where the action is null but the terminal hasn't rerendered yet (due to its own debounce) to remove the timer.

File: src/Terminal/ui/TerminalActionTimer.tsx (hunk 1 above)
Comment (bezrodnov) [reply src/Terminal/ui/TerminalActionTimer.tsx]: Good catch! 👍
I did not even check how often this event is emitted when I created the PR.

It's indeed called approximately every 200ms. I've decided to use the alternative approach since it's cleaner (less code). And we don't need to check if the action is null there because in this case component is already unmounted.

Comment (bezrodnov) [reply src/Terminal/ui/TerminalActionTimer.tsx]: > And we don't need to check if the action is null there because in this case component is already unmounted.

we actually do need to do that 😅 - after some testing (with reduced rerender timeouts) I got an error because of that.
wip...

Comment (bezrodnov) [reply src/Terminal/ui/TerminalActionTimer.tsx]: @Snarling could you please review the latest version?

Comment (Snarling) [reply src/Terminal/ui/TerminalActionTimer.tsx]: https://github.com/bitburner-official/bitburner-src/assets/84951833/31acac28-5b83-48eb-932d-655349e343b4

Not sure if this can happen if the main process loop isn't delayed (e.g. by a script keeping the main process busy), but I was able to get this error by running a script that causes delays in the main engine loop and then just backdooring n00dles repeatedly. This will happen any time that the action has ended (so there's no action to make a bar out of) but the actual terminal has not rerendered yet because even though it got the event trigger from the action finishing, it's a debounced event so it won't happen right away.

Comment (Snarling) [reply src/Terminal/ui/TerminalActionTimer.tsx]: Just saw your update, that should be fine to avoid the issue.

**Review by Snarling — APPROVED** [review]

File: src/Terminal/ui/TerminalActionTimer.tsx (hunk 1 above)
Comment (bezrodnov) [reply src/Terminal/ui/TerminalActionTimer.tsx]: yeah, I just made a wrong assumption that setting the action to null will unmount the progress bar before its rerender is called. The main reason here is that action is not a react state - so changing the action value does not trigger any re-renders directly.

Thanks for the review and valuable advice!
