### PR TITLE
INFILTRATION: Improve accuracy of slash game UI

### LINKED ISSUE #1402: Shadows of Anarchy Ares augmentation doesn't always work.
image

I'm not completely sure how to reproduce it. I had trouble with this a few days ago, but it was working yesterday. Then it started again today. I'm just doing manual infiltrations, and the timer provided by the Ares augmentation is wrong.

Playing on v2.6.2dev (18ae6ce21).

### PR DESCRIPTION
**Pull request by catloversg**
New change: If the player has `MightOfAres`, the logic of phase 1 only starts after the "special" `GameTimer` expires.

Fixes #1402.

### CODE REVIEW

File: src/Infiltration/ui/SlashGame.tsx [hunk 1]
```diff
@@ -27,34 +27,52 @@ const difficulties: {
...
-    setPhase(0);
-    setGuardingTime(guardingTime);
-    setHasAugment(Player.hasAugmentation(AugmentationName.MightOfAres, true));
+    return {
+      hasAugment: Player.hasAugmentation(AugmentationName.MightOfAres, true),
+      guardingTime,
+      distractedTime,
+      alertedTime,
+    };
+  }, [difficulty]);
```
Comment (d0sboots) [inline src/Infiltration/ui/SlashGame.tsx]: You're memoizing the augment state here... isn't it possible for it to change without this component getting re-rendered as a result?
