### PR TITLE
BUGFIX: Saved running scripts are started before SWC is initialized

### LINKED ISSUE #1853: TypeScript scripts crash on game load
# Overview

In version v2.7.0 (fbe1546fd) `*.ts` script that are running on game save crash with a message `Script crashed due to an error.` when you load the game. `*.js` scripts work as expected and start running again on game load.

# Reproduction

Run both of the scripts in the attached archive. Save the game, close it and load the savegame. The .js file starts running again, while the .ts script crashes.
[crashtest.zip](https://github.com/user-attachments/files/18141751/crashtest.zip)

### PR DESCRIPTION
**Pull request by catloversg**
Saved running scripts are started in `Engine.load`, but `Engine.load` is called at the same time as `initSwc`. Therefore, SWC is usually not initialized when we use it to transform TS scripts.

Fixes #1853.

### CODE REVIEW

File: src/ui/LoadingScreen.tsx [hunk 1]
```diff
@@ -34,8 +34,9 @@ export function LoadingScreen(): React.ReactElement {
   });
 
   useEffect(() => {
-    load()
-      .then((saveData) => Promise.all([initSwc(), Engine.load(saveData)]))
+    initSwc()
```
Comment (d0sboots) [inline src/ui/LoadingScreen.tsx]: initSwc just needs to happen before `Engine.load`, not `load()`, right?
To save some time on init (hopefully) can we `Promise.all([initSwc, load()]).then(Engine.load())`?
