### PR TITLE
BUGFIX: Fix wrong HP after calling applyEntropy

### LINKED ISSUE #1308: Hyperbolic Regeneration Chamber not working properly
After loosing health doing Bladeburner actions, if I choose to heal by using the action "Hyperbolic Regeneration Chamber" the health will heal by 2 points then shortly after reduces by 2 points again automatically.
I've noticed this behavior initially while running an automation script for Bladeburner actions.
Killing the script and choosing the action manually has the same result.
Player health regenerates by two and then shortly after reduces by two.

Only way to heal at the moment is by using Hospital.

Game Version: {"version":"2.6.1","commit":"d2c7b2504","platform":"Steam"}

### PR DESCRIPTION
**Pull request by catloversg**
In `updateSkillLevels`, we recalculate the skill levels of stats based on exp and stats' multipliers. After that, we calculate new values for `hp.current` and `hp.max`. In `applyEntropy`, we change stats' multipliers and call `updateSkillLevels` four times. After that, the HP value is wrong.

Log:
```
regenerateHp before 5 57
regenerateHp after 7 57
new engine update
Error
    at PlayerObject.updateSkillLevels (PersonMethods.ts:136:7)
    at PlayerObject.reapplyAllAugmentations (PlayerObjectGeneralMethods.ts:405:8)
    at PlayerObject.applyEntropy (PlayerObjectAugmentationMethods.ts:18:8)
    at StaneksGift.process (StaneksGift.ts:71:51)
    at Object.updateGame (engine.tsx:106:60)
    at start (engine.tsx:393:14)
updateSkillLevels before 7 57 0.12280701754385964
updateSkillLevels after 4 32 0.125
Error
    at PlayerObject.updateSkillLevels (PersonMethods.ts:136:7)
    at PlayerObject.reapplyAllSourceFiles (PlayerObjectGeneralMethods.ts:421:8)
    at PlayerObject.applyEntropy (PlayerObjectAugmentationMethods.ts:19:8)
    at StaneksGift.process (StaneksGift.ts:71:51)
    at Object.updateGame (engine.tsx:106:60)
    at start (engine.tsx:393:14)
updateSkillLevels before 4 32 0.125
updateSkillLevels after 5 42 0.11904761904761904
Error
    at PlayerObject.updateSkillLevels (PersonMethods.ts:136:7)
    at StaneksGift.updateMults (StaneksGift.ts:221:49)
    at PlayerObject.applyEntropy (PlayerObjectAugmentationMethods.ts:21:58)
    at StaneksGift.process (StaneksGift.ts:71:51)
    at Object.updateGame (engine.tsx:106:60)
    at start (engine.tsx:393:14)
updateSkillLevels before 5 42 0.11904761904761904
updateSkillLevels after 6 54 0.1111111111111111
Error
    at PlayerObject.updateSkillLevels (PersonMethods.ts:136:7)
    at updateGoMults (effect.ts:74:47)
    at PlayerObject.applyEntropy (PlayerObjectAugmentationMethods.ts:22:68)
    at StaneksGift.process (StaneksGift.ts:71:51)
    at Object.updateGame (engine.tsx:106:60)
    at start (engine.tsx:393:14)
updateSkillLevels before 6 54 0.1111111111111111
updateSkillLevels after 6 57 0.10526315789473684
new engine update
```

How to reproduce:
- Load the save file in #1308.
- Kill all scripts and reload.
- Run `run stanek.js`.
- Deal damage to the player.
- Set BB action to Hyperbolic Regeneration Chamber.

Fixes #1308.

### CODE REVIEW

File: src/PersonObjects/Player/PlayerObjectAugmentationMethods.ts [hunk 1]
```diff
@@ -6,11 +6,29 @@ import { updateGoMults } from "../../Go/effects/effect";
...
+
   // Re-apply all multipliers
   this.reapplyAllAugmentations();
   this.reapplyAllSourceFiles();
 
   this.mults = calculateEntropy(stacks);
   staneksGift.updateMults();
   updateGoMults();
+
+  if (this.hp.max === currentMaxHp) {
```
Comment (d0sboots) [inline src/PersonObjects/Player/PlayerObjectAugmentationMethods.ts]: Simplifications: I don't think you need this `if` at all. If the max is unchanged, the round below will ensure that the same hp value is calculated. 

Given that, you can calculate and save the ratio at the top, which makes both the expression and explanation simpler.

**Comment by d0sboots** [comment]
Nice debugging!

I'd this the only place that is potentially affected? I could see this creeping up on other places that futz with modifiers (like stanek).

**Comment by catloversg** [comment]
AFAIK, this is the only place that is affected. This bug is caused by doing a specific action (changing multipliers + calling `updateSkillLevels`) multiple times at once. Each time we do that, the HP ratio may shift slightly. Doing that multiple times makes the HP ratio shift too much, and the current HP is set to the wrong value.

`applyEntropy` is the only place that does it. Many places update multipliers and apply special effects by calling `applyEntropy` (Staneks Gift, Go, Grafting, etc.).

By the way, the CI test check throws a fit at `StockMarket.test.ts` again. We can ignore it.
