### PR TITLE
MISC: Prevent running multiple instances of Electron app

### LINKED ISSUE #2055: Error: Failed to get IDB (at "Loading Screen")
### How did this happen?
because I have the game pined to my taskbar so I accidentally clicked it when I was on a different window. the recovery mode was activated while I was loading the game. When I saw two windows of it I closed the one without any text on the main part of the window where the game is played. the tools bar did appear on the window I closed but not the loading text. I believe that this is due to a missing redundancy in the conflicting save system. 

I am going to submit a similar report on discord to allow for you to contact me, thank you for making this game.
###Please fill this information with details if relevant.

- [ ] Save file
- [ ] Minimal scripts to reproduce the issue
- [ ] Steps to reproduce

### Environment

* Error: Error: Failed to get IDB
* Page: Loading Screen
* Version: v2.8.0 (3b58f9c0c)
* Environment: Production
* Platform: Steam
* UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) bitburner/2.8.0 Chrome/122.0.6261.156 Electron/29.4.5 Safari/537.36
* Features: lang=en-US cookiesEnabled=true doNotTrack=null indexedDb=true
* Source: undefined

### Stack Trace
```
Error: Failed to get IDB
    at n.onerror (file:///C:/Program%20Files%20(x86)/Steam/steamapps/common/Bitburner/resources/app/dist/main.bundle.js:9:891013)
```

### React Component Stack
```
undefined
```

### Save
```
I save twice a day once at the beginning and once at the end. I always overwrite the previous save

[bitburnerSave_1742539241_BN1x1.json.gz](https://github.com/user-attachments/files/19496101/bitburnerSave_1742539241_BN1x1.json.gz)

```

### PR DESCRIPTION
**Pull request by catloversg**
When the Electron app is running, it puts locks on some files related to IndexedDB. When the app is launched multiple times, it cannot access IndexedDB data and create the crash in #2055. This PR adds a check to see where the app is launched multiple times. If it is, the second instance shows an error popup and then quits.

Capture

Closes #2055.

### CODE REVIEW

File: electron/main.js [hunk 1]
```diff
@@ -219,6 +232,14 @@ app.on("ready", async () => {
     await utils.exportSave(window);
   } else {
     const window = await startWindow(process.argv.includes("--no-scripts"));
+    app.on("second-instance", (event, commandLine, workingDirectory, additionalData) => {
```
Comment (d0sboots) [inline electron/main.js]: Like the example in the docs, let's put this right up next to the lock checking code. Keeps it easier to think about related stuff together.
