### PR TITLE
UI: Fix clipped numbers when values are too big in Augmentations page

### LINKED ISSUE #614: Augmentations page loses some far right values
When have big numbers some values are not visible/clipped from the right side.

2023-06-15 14_22_16-Bitburner v2 3 1 (100030008) Bug
2023-06-15 14_27_01-Bitburner v2 3 1 (100030008)_Bug2

### PR DESCRIPTION
**Pull request by catloversg**
Before:
before

After:
after

Fixes #614.

### CODE REVIEW

File: src/Augmentation/ui/PlayerMultipliers.tsx [hunk 1]
```diff
@@ -23,14 +23,22 @@ interface IBitNodeModifiedStatsProps {
   color: string;
 }
 
+function customFormatPercent(value: number): string {
+  if (value >= 100) {
```
Comment (d0sboots) [inline src/Augmentation/ui/PlayerMultipliers.tsx]: I don't get the purpose of this `if`. It's duplicating a check that happens inside `formatPercent`; shouldn't `formatPercent(value, 2, 100)` work the same unconditionally?
