### PR TITLE
CONTRACTS: Display contract answers on completely failed contracts

### LINKED ISSUE #2411: Return correct answer when contract self-destructs
When a contract self-destructs, it would be useful for it to return what answer it would have accepted. It would be too late to be useful in gaining the reward, but might be helpful in debugging the code that was failing.

So instead of:

```
[home /]> run contract-190576.cct 
Contract FAILED - Contract is now self-destructing
```

We would get

```
[home /]> run contract-190576.cct 
Contract FAILED - Contract is now self-destructing. Correct answer: "8nnZnKdKs380215Uteo3258N0XWkErO750919FfhSZk67L02q373"//
```

### PR DESCRIPTION
**Pull request by TheCleric**
closes #2411

### CODE REVIEW

File: src/CodingContract/ContractTypes.ts [hunk 1]
```diff
@@ -33,6 +33,8 @@ interface CodingContractType<Data, Answer, State = Data> {
   difficulty: number;
   /** Function that generates a valid 'state' for a contract type */
   generate: () => State;
+  /** Function that returns an answer, if possible, for a given contract */
+  getAnswer: (data: Data) => Answer | null;
```
Comment (d0sboots) [inline src/CodingContract/ContractTypes.ts:37]: This is the wrong type, but I think it would work better to use this type.
What you wrote is a function that returns an Answer or null, but getAnswer always returns an Answer (when it is defined). However, I think it will make everything much simpler if you adopt this as the type and then remove all the complex type stuff you're trying. Just have the contracts that don't return an answer return null. We don't need the ability to distinguish them at compile time.

Comment (TheCleric) [reply src/CodingContract/ContractTypes.ts:37]: > This is the wrong type, but I think it would work better to use this type. What you wrote is a function that returns an Answer or null, but getAnswer always returns an Answer (when it is defined). However, I think it will make everything much simpler if you adopt this as the type and then remove all the complex type stuff you're trying. Just have the contracts that don't return an answer return null. We don't need the ability to distinguish them at compile time.

Sorry I forgot I had the mixture in here. Your thinking is the same as mine. I had started the path of making it so getAnswer may or may not be there, but it is much easier and less clunky to always have it, but it returns null on contract types without a defined answer.

I'll proceed on that path if you think this is promising.

**Comment by TheCleric** [comment]
Of note here, the following contract types will always return null:

- Square root => as discussed.
- Shortest Path In A Grid => as we don't really generate an answer as much as calculate what the minimum steps it would take and make sure the answer conforms. We COULD generate an answer, but did not want to inject any sort of solution finder into the code.
- Proper 2 Coloring Of A Graph => similar to above

File: src/CodingContract/contracts/ArrayJumpingGame.ts [hunk 2]
```diff
@@ -105,7 +108,10 @@ export const arrayJumpingGame: Pick<
         lastJump = jumpedFrom;
         jumps++;
       }
-      return jumps === answer;
+      return jumps;
+    },
+    solver: (data, answer) => {
+      return arrayJumpingGame[CodingContractName.ArrayJumpingGame].getAnswer(data) === answer;
```
Comment (catloversg) [inline src/CodingContract/contracts/ArrayJumpingGame.ts]:
```suggestion
      return arrayJumpingGame[CodingContractName.ArrayJumpingGameII].getAnswer(data) === answer;
```

File: src/CodingContract/contracts/Compression.ts [hunk 3]
```diff
@@ -97,6 +100,9 @@ export const compression: Pick<
     generate: (): string => {
       return comprLZEncode(comprLZGenerate());
     },
+    getAnswer: (compr) => {
+      return comprLZDecode(compr) ?? "";
+    },
     solver: (compr, answer) => {
       return (comprLZDecode(compr) ?? "") === answer;
```
Comment (catloversg) [inline src/CodingContract/contracts/Compression.ts]: You should use the pattern `return foo[CodingContractName.Bar].getAnswer(baz) === answer;` here and some other places.

File: src/CodingContract/contracts/Compression.ts [hunk 4]
```diff
@@ -135,6 +141,9 @@ export const compression: Pick<
     generate: (): string => {
       return comprLZGenerate();
     },
+    getAnswer: (plain) => {
+      return comprLZEncode(plain);
+    },
     solver: (plain, answer) => {
       return answer.length <= comprLZEncode(plain).length && comprLZDecode(answer) === plain;
```
Comment (catloversg) [inline src/CodingContract/contracts/Compression.ts]: Same here.

File: src/CodingContract/contracts/FindAllValidMathExpressions.ts [hunk 5]
```diff
@@ -86,7 +86,12 @@ export const findAllValidMathExpressions: Pick<CodingContractTypes, CodingContra
       const result: string[] = [];
       helper(result, "", num, target, 0, 0, 0);
 
-      if (result.length !== answer.length) return false;
+      return result;
+    },
+    solver: (data, answer) => {
+      const result = findAllValidMathExpressions[CodingContractName.FindAllValidMathExpressions].getAnswer(data);
+
+      if (result === null || result.length !== answer.length) return false;
```
Comment (catloversg) [inline src/CodingContract/contracts/FindAllValidMathExpressions.ts]: `getAnswer` can return null (with 3 contracts now), but in this contract, it cannot return null. If it's null here, there must be a bug in `getAnswer`, and we should notify both the player and ourselves. `exceptionAlert` is useful in this case.

File: src/CodingContract/contracts/GenerateIPAddresses.ts [hunk 6]
```diff
@@ -51,6 +51,10 @@ export const generateIPAddresses: Pick<CodingContractTypes, CodingContractName.G
         }
       }
 
+      return ret;
+    },
+    solver: (data, answer) => {
+      const ret = generateIPAddresses[CodingContractName.GenerateIPAddresses].getAnswer(data) as string[];
```
Comment (catloversg) [inline src/CodingContract/contracts/GenerateIPAddresses.ts]: In general, we restrict the usage of typecasting as much as possible. If we do it, there must be a very good reason, and that reason must be explained in the comments. In this case, typecasting is not acceptable. You need to check the null case. Please check my comment in `FindAllValidMathExpressions`.

File: src/CodingContract/contracts/HammingCode.ts [hunk 7]
```diff
@@ -36,6 +36,9 @@ export const hammingCode: Pick<
       const y = Math.pow(2, getRandomIntInclusive(1, 57));
       return getRandomIntInclusive(Math.min(x, y), Math.max(x, y));
     },
+    getAnswer: (data) => {
+      return HammingEncode(data);
+    },
     solver: (data, answer) => {
       return HammingEncode(data) === answer;
```
Comment (catloversg) [inline src/CodingContract/contracts/HammingCode.ts]: Same here.

File: src/CodingContract/contracts/HammingCode.ts [hunk 8]
```diff
@@ -83,6 +86,9 @@ export const hammingCode: Pick<
       }
       return _buildArray.join("");
     },
+    getAnswer: (data) => {
+      return HammingDecode(data);
+    },
     solver: (data, answer) => {
       return HammingDecode(data) === answer;
```
Comment (catloversg) [inline src/CodingContract/contracts/HammingCode.ts]: Same here.

File: src/CodingContract/contracts/MergeOverlappingIntervals.ts [hunk 9]
```diff
@@ -50,6 +50,14 @@ export const mergeOverlappingIntervals: Pick<CodingContractTypes, CodingContract
       }
       result.push([start, end]);
 
+      return result;
+    },
+    solver: (data, answer) => {
+      const result = mergeOverlappingIntervals[CodingContractName.MergeOverlappingIntervals].getAnswer(data) as [
```
Comment (catloversg) [inline src/CodingContract/contracts/MergeOverlappingIntervals.ts]: Same comment about typecasting.

File: src/CodingContract/contracts/Proper2ColoringOfAGraph.ts [hunk 10]
```diff
@@ -75,6 +75,10 @@ export const proper2ColoringOfAGraph: Pick<CodingContractTypes, CodingContractNa
 
       return [n + m, edges];
     },
+    getAnswer: () => {
+      // Not quite sure how we can use the below to generate a canonical "answer"
```
Comment (catloversg) [inline src/CodingContract/contracts/Proper2ColoringOfAGraph.ts]: You don't need to write this comment. Just remove it.

There is no need to note that the PR's contributor is not sure whether the contract can generate an answer. With this PR, by default, if a contract cannot generate an answer, it will return null. If it can but it returns null, that's either a bug (and we will fix it) or a deliberate choice. If that's a deliberate choice, you need to rephrase this comment and explain the reason that you don't want to generate the answer.

File: src/CodingContract/contracts/SanitizeParenthesesInExpression.ts [hunk 11]
```diff
@@ -94,6 +94,13 @@ export const sanitizeParenthesesInExpression: Pick<
 
       dfs(0, 0, left, right, data, "", res);
 
+      return res;
+    },
+    solver: (data, answer) => {
+      const res = sanitizeParenthesesInExpression[CodingContractName.SanitizeParenthesesInExpression].getAnswer(
```
Comment (catloversg) [inline src/CodingContract/contracts/SanitizeParenthesesInExpression.ts]: Same comment about typecasting.

File: src/CodingContract/contracts/ShortestPathInAGrid.ts [hunk 12]
```diff
@@ -53,6 +53,10 @@ export const shortestPathInAGrid: Pick<CodingContractTypes, CodingContractName.S
 
       return grid;
     },
+    getAnswer: () => {
+      // Not sure if we can use the below to generate a canonical answer
```
Comment (catloversg) [inline src/CodingContract/contracts/ShortestPathInAGrid.ts]: Remove this comment.

File: src/CodingContract/contracts/SpiralizeMatrix.ts [hunk 13]
```diff
@@ -107,6 +107,10 @@ export const spiralizeMatrix: Pick<CodingContractTypes, CodingContractName.Spira
         }
       }
 
+      return spiral;
+    },
+    solver: (data, answer) => {
+      const spiral = spiralizeMatrix[CodingContractName.SpiralizeMatrix].getAnswer(data) as number[];
```
Comment (catloversg) [inline src/CodingContract/contracts/SpiralizeMatrix.ts]: Same comment about typecasting.

File: src/NetscriptFunctions/CodingContract.ts [hunk 14]
```diff
@@ -55,6 +55,11 @@ export function NetscriptCodingContract(): InternalAPI<ICodingContract> {
       case CodingContractResult.Failure: {
         if (++contract.tries >= contract.getMaxNumTries()) {
           helpers.log(ctx, () => `Coding Contract attempt '${contract.fn}' failed. Contract is now self-destructing`);
+          const solution = contract.getAnswer();
+          if (solution !== null) {
+            helpers.log(ctx, () => "Coding Contract solution was");
```
Comment (catloversg) [inline src/NetscriptFunctions/CodingContract.ts]: You should also do this with `runContract` in `src\Terminal\Terminal.ts`.

Optional: Consider printing the answer on the same line of `Coding Contract solution was` unless it's too hard to read in too many cases. With a number or an array, printing them on the same line looks good.

Comment (d0sboots) [reply src/NetscriptFunctions/CodingContract.ts]: +1 especially to showing the answer in the manual case; I was gonna mention that myself. 

I agree with all the other points.

File: src/CodingContract/contracts/ArrayJumpingGame.ts (hunk 2 above)
Comment (TheCleric) [reply src/CodingContract/contracts/ArrayJumpingGame.ts]: Good catch!

**Review by catloversg — APPROVED** [review]
