### PR TITLE
MISC: Dynamically load imported scripts for editor

### LINKED ISSUE #1877: Autocompletion does not work in the editor anymore
Since TS files are allowed, the auto completion does not work for js files anymore in my savegame.
The tooltip on {NS} also does not work as before anymore.
It does however work in a new game.

After some more testing: It works if I stay in the editor for a long time. The loading time is much longer now.

- [x] Save: 
[bitburnerSave_1734918884_BN12x153.json.gz](https://github.com/user-attachments/files/18224213/bitburnerSave_1734918884_BN12x153.json.gz)

- [x] Minimal scripts to reproduce the issue
```
/** @param {NS} ns */
export async function main(ns) {
	ns. // auto completion is not triggered here
}
```
- [x] Steps to reproduce: Open the editor testA.js and try to get auto completion for any method of NS
- [x] v2.7.0, v2.7.1dev

### PR DESCRIPTION
**Pull request by catloversg**
For context, please check my comment at https://github.com/bitburner-official/bitburner-src/issues/1747#issuecomment-2558912702.

This PR fixes that problem by dynamically loading only imported scripts instead of loading all scripts.

Note: This PR conflicts with #1865 and #1866, so I ported those fixes to this PR.

How to test:
Test 1:
- Load this save file: [test suite for editor.gz](https://github.com/user-attachments/files/18310863/test.suite.for.editor.gz)
- Open all scripts, especially `ts.ts` and `tsx.tsx`. False-positive error markers should disappear after 2 seconds.

Test 2:
- Load the save file in #1877.
- Make sure that autocomplete works normally.

Closes #1877.

### CODE REVIEW

File: src/ScriptEditor/ui/ScriptEditorRoot.tsx [hunk 1]
```diff
@@ -62,6 +74,91 @@ function Root(props: IProps): React.ReactElement {
     (editorElement as HTMLElement).style.outline = "none";
   }, [editorRef]);
 
+  /**
+   * The TypeScript compiler needs time to perform type-checking, so in some edge cases, the editor shows the 2792 error
```
Comment (d0sboots) [inline src/ScriptEditor/ui/ScriptEditorRoot.tsx:78]: Thank you for this comment. The whole thing makes me :sob:, but such is Monaco.

File: src/ScriptEditor/ui/ScriptEditorRoot.tsx [hunk 2]
```diff
@@ -62,6 +74,91 @@ function Root(props: IProps): React.ReactElement {
...
+    if (!currentScript || !editorRef.current) {
+      return;
+    }
+    const markers = monaco.editor.getModelMarkers({
+      resource: currentScript.model.uri,
+    });
+    let needToReloadModel = false;
+    for (const marker of markers) {
+      // 2792: "Cannot find module" error
+      if (marker.code !== "2792") {
```
Comment (d0sboots) [inline src/ScriptEditor/ui/ScriptEditorRoot.tsx:106]: If a module legitimately can't be found, will this reload the module every 2 seconds? Is that a problem?

Comment (catloversg) [reply src/ScriptEditor/ui/ScriptEditorRoot.tsx:106]: If a module does not exist, `makeModelsForImports` will throw an error at `walk.simple` before calling `reloadModelOfCurrentScript`. It looks like this:

Capture

Even in the case that there is a valid error marker (not import errors), `reloadModelOfCurrentScript` is only called when the player edits the code. I don't see any way that it is called every 2 seconds, unless the player constantly changes the code, which is a valid case that `reloadModelOfCurrentScript` needs to be called.
