### PR TITLE
UI: Automatically show Bitverse UI if BN is finished

### LINKED ISSUE #1325: When switching bitnodes if the auto save has not occurred and you close the game it could leave you in a bad state.
Bitburner v.2.6.1 (d2c7b2504)

Steps to reproduce:
Destroy bitnode and choose a different bit node, e.g. 1.3 to 2.1.  Quit game before auto save occurs.

Observation:
When starting Bitburner it loads the last save file which occurred before you destroyed the bitnode.  If you have already backdoored world demon you wind up in a stuck state.  No b1tflume.exe either to exit.  You are essentially in a broken state and will need to reload from last save.

Expected:
Game loads fine and maintains previous state. 

Suggestion:
A quick fix for this could be to just autosave when switching bitnodes.  That will ensure the local save file matches and won't leave you in a broken state.

### PR DESCRIPTION
**Pull request by catloversg**
Fixes #1325.

### CODE REVIEW

**Comment by Kelenius** [comment]
Am I reading this correctly that if you have finished the last black OP, the game will immediately throw you out of the bitnode?

**Comment by catloversg** [comment]
It will show the Bitverse UI the next time the game is loaded, not immediately after finishing the last BlackOps. I can make a special case for it (only automatically show Bitverse UI if WD is backdoored).

File: src/PersonObjects/Player/PlayerObject.ts [hunk 1]
```diff
@@ -132,6 +132,9 @@ export class PlayerObject extends Person implements IPlayer {
   sourceFileLvl = generalMethods.sourceFileLvl;
   applyEntropy = augmentationMethods.applyEntropy;
   focusPenalty = generalMethods.focusPenalty;
+  bitNodeFinishedState = generalMethods.bitNodeFinishedState;
+  canAccessBitNodeFeature = generalMethods.canAccessBitNodeFeature;
```
Comment (d0sboots) [inline src/PersonObjects/Player/PlayerObject.ts]: What is the purpose of moving these methods onto `Player`? It's a god-object, and IMO we should avoid expanding it further. I can see the logic for sharing `bitNodeFinishedState` (although there are other ways it could be shared, probably), but the other two are only used for the achievements I think?

**Review by d0sboots — COMMENTED** [review]
I think what would be most consistent would be for "WD backdoored" to be the definitive determination of "you have beaten the node." So clicking the button at the end of Bladeburner would apply backdoor; any other alternate victory conditions would do the same.

This simplifies the logic in `bitNodeFinishedState` and makes it easy to know when we should start showing the selection screen. (It's exactly the same logic.)

File: src/Achievements/Achievements.ts [hunk 2]
```diff
@@ -61,18 +60,11 @@ export interface AchievementData {
...
+function canAccessBitNodeFeature(bitNode: number): boolean {
+  return Player.bitNodeN === bitNode || Player.sourceFileLvl(bitNode) > 0;
 }
 
-function hasAccessToSF(bn: number): boolean {
-  return Player.bitNodeN === bn || Player.sourceFileLvl(bn) > 0;
-}
-
-function knowsAboutBitverse(): boolean {
+function knowAboutBitverse(): boolean {
```
Comment (d0sboots) [inline src/Achievements/Achievements.ts]: Typo when you reverted this
